# Generated by Django 6.0.5 on 2026-07-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'verbose_name': 'Detailed Weather Info', 'verbose_name_plural': 'Detailed Weather Info'},
        ),
    ]
