# Generated by Django 6.0.5 on 2026-05-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weatherquery_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherquery',
            name='forecast_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
