# Generated by Django 6.0.5 on 2026-06-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_usersearchhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersearchhistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='usersearchhistory',
            name='result_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
