# Generated by Django 6.0.5 on 2026-07-01 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_alter_usersearchhistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='usersearchhistory',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Search Log', 'verbose_name_plural': 'Search Logs'},
        ),
        migrations.AlterModelOptions(
            name='weatherquery',
            options={'verbose_name': 'Weather Forecast', 'verbose_name_plural': 'Weather Forecasts'},
        ),
        migrations.AlterField(
            model_name='weatherquery',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.location'),
        ),
    ]
