# Generated by Django 6.0.5 on 2026-07-02 16:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_weatherlocation_alter_weatherquery_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherquery',
            name='forecast_hour',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AlterField(
            model_name='weatherquery',
            name='forecast_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name='weatherquery',
            unique_together={('location', 'forecast_date', 'forecast_hour')},
        ),
    ]
