# Generated by Django 6.0.5 on 2026-07-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_weatherquery_forecast_hour_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherlocation',
            options={'verbose_name': 'Weather Location', 'verbose_name_plural': 'Weather Locations'},
        ),
    ]
