@baseUrl = http://127.0.0.1:8000/api

### GET JWT token
POST {{baseUrl}}/users/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "root",
    "password": "root"
}

### GET forecast
GET {{baseUrl}}/weather/forecast/?location=Tokyo HTTP/1.1
Content-Type: application/json

### GET forecast
GET {{baseUrl}}/weather/forecast/?location=Tokyo HTTP/1.1
Content-Type: application/json
Authorization: Bearer 

### POST forecast
POST {{baseUrl}}/weather/forecast/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwMzE1MzMwLCJpYXQiOjE3ODAzMTUwMzAsImp0aSI6ImM3NTI5OTI5MDIwMjRhMzE5M2UwMDBlNDFiNGE3YzM1IiwidXNlcl9pZCI6IjEifQ.lTU54GxXa7Gb8nkCwIUmgPN4d_j-fMGAFbN1IA_UpwY

{
    "location": "Tokyo",
    "forecast_date": "2026-05-31T15:54",
    "temperature": 25,
    "condition": "Rain"
}

### DELETE forecast
DELETE {{baseUrl}}/weather/forecast/22 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwMjM3MDI4LCJpYXQiOjE3ODAyMzY3MjgsImp0aSI6ImRjMGU5ZWM2ZmU1ODQwODc5MDYzNDg3Njk1NjQ5NjJmIiwidXNlcl9pZCI6IjEifQ.PkdTVVbqyITeSNYc9x-OuSt8N2XJA28P3Kk8xVj-9L0

### PUT forecast
PUT {{baseUrl}}/weather/forecast/19 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwMjM3MjYyLCJpYXQiOjE3ODAyMzY5NjIsImp0aSI6IjNlYzFiYTA5NmI4ZjRjYTdiZGIzZDVkMzBlNmZiNGI5IiwidXNlcl9pZCI6IjEifQ.iYSl5l_FbBO6xFv4KjIh77xIKoDkYHHY1gZXf6k0O3I

{
    "location": "Tokyo",
    "temperature": 2.5,
    "condition": "Sunnyq",
    "forecast_date": "2026-06-03T13:53:49.887296Z"
}

#   {
#     "id": 19,
#     "location": "Tokyo",
#     "temperature": 2.2,
#     "condition": "Sunny",
#     "forecast_date": "2026-06-03T13:52:49.887296Z"
#   }