@baseUrl = http://127.0.0.1:8000/api

### GET JWT token
POST {{baseUrl}}/users/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "",
    "password": ""
}


### GET forecast
GET {{baseUrl}}/weather/forecast/?location=Tokyo HTTP/1.1
Content-Type: application/json
Authorization: Bearer 