@baseUrl = http://127.0.0.1:8000/api

### GET JWT token
POST {{baseUrl}}/users/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "root",
    "password": "root"
}

### GET forecast
GET {{baseUrl}}/weather/forecast/?location=Tokyo HTTP/1.1
Content-Type: application/json
Authorization: Bearer 

### POST forecast
POST {{baseUrl}}/weather/forecast/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwMjMyNzQwLCJpYXQiOjE3ODAyMzI0NDAsImp0aSI6IjZhZTc5MTc3NWJkMDQ1Mzc4ZDgxZmU5ODQxZTI1MGUxIiwidXNlcl9pZCI6IjEifQ.__ucp8CMQI10b5KsTH9lBZtei3O7YutmusHAPFlkxas