# Generated by Django 6.0.5 on 2026-05-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('admin', 'Admin')], default='standard', max_length=10),
        ),
    ]
